### ISSUE TITLE
Plugin Enable Issue

### ISSUE THREAD

**Issue by XanderLim** [ParzivalExe/guiapi#1]
Hello, this is my first time on report of the issue.
So what i was expecting it is to work but instead,
i get this issue saying:

17:39:18 [SEVERE] Error occurred while enabling GuiAPI v1.2 (Is it up to date?): org.bukkit.plugin.PluginManager.registerEvents(Lorg/bukkit/event/Liste
lugin/Plugin;)V
java.lang.NoSuchMethodError: org.bukkit.plugin.PluginManager.registerEvents(Lorg/bukkit/event/Listener;Lorg/bukkit/plugin/Plugin;)V
        at com.bluebird.api.gui.GuiApiInitializer.registerEvents(GuiApiInitializer.java:51)
        at com.bluebird.api.gui.GuiApiInitializer.onEnable(GuiApiInitializer.java:34)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:174)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:957)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:280)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:171)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:154)
        at net.minecraft.server.MinecraftServer.e(MinecraftServer.java:297)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:284)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:152)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:348)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

I downloaded the guiapi plugin which it should actually worked on beta 1.8.1.
Iam using beta 1.8.1 server.

**Comment by ParzivalExe** [comment]
Sorry, that you had to wait sooo long for an answer, but I had several Problems with not-working E-Mails and more. 

Do you have already programmed something with this API or is the API crashing before you even started programming?

**Comment by XanderLim** [comment]
The api crashed before i even started programming

**Comment by ParzivalExe** [comment]
Because of how old this issue is and the fact that there now is [v2.0](https://github.com/ParzivalExe/guiapi/wiki/Version-2.0) available which is a complete rework of the entire API I will close this issue. 

If you indeed try the API again and the issue persists even with v2.0 you can simply reply again or even open up a new issue.
